version: '3.8'

services:
  db:
    image: postgres:13
    container_name: djangoexam_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: djangoexamdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - djangoexam_network

  adminer:
    image: adminer
    container_name: djangoexam_adminer
    ports:
      - "8081:8080"
    networks:
      - djangoexam_network
  redis:
    image: redis:latest
    container_name: djangoexam_redis
    ports:
     - "6379:6379"
    networks:
     - djangoexam_network  
    environment:
     - TZ=Asia/Baku

  celery:
   build: .
   container_name: djangoexam_celery
   command: celery -A celery_config worker -l info
   depends_on:
    - redis
    - db
   networks:
    - djangoexam_network
   environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - DJANGO_SETTINGS_MODULE=djangoexamproject.settings
    - TZ=Asia/Baku  # Set the desired timezone
    - POSTGRES_HOST=db 
    - POSTGRES_PORT=5432 
   volumes:
    - /etc/localtime:/etc/localtime:ro  # Sync the container's timezone with the host
    - /etc/timezone:/etc/timezone:ro    # For additional timezone information (optional)

  celery-beat:
   build: .
   container_name: djangoexam_celery_beat
   command: celery -A celery_config beat -l info
   depends_on:
    - redis
    - db
   networks:
    - djangoexam_network
   environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - DJANGO_SETTINGS_MODULE=djangoexamproject.settings
    - TZ=Asia/Baku  # Set the desired timezone
    - POSTGRES_HOST=db 
    - POSTGRES_PORT=5432 
   volumes:
    - /etc/localtime:/etc/localtime:ro  # Sync the container's timezone with the host
    - /etc/timezone:/etc/timezone:ro    # For additional timezone information (optional)

  
volumes:
  postgres_data:
networks:
  djangoexam_network:
    driver: bridge
