# Generated by Django 5.1.2 on 2024-11-04 07:22

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
    ]
